# Dockerfile.dev
FROM ruby:3.2.2

# 必要なパッケージをインストール
RUN apt-get update -qq && \
    apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    npm \
    libvips \
    libvips-dev \
    libvips-tools \
    && rm -rf /var/lib/apt/lists/*

# yarn をインストール
RUN npm install -g yarn

# 作業ディレクトリを設定
WORKDIR /myapp

# Gemfile と Gemfile.lock をコピー
COPY Gemfile Gemfile.lock ./

# bundler をインストール
RUN gem install bundler && bundle install

# アプリケーションのコードをコピー
COPY . .

# ポートを公開
EXPOSE 3000

# サーバーを起動
CMD ["rails", "server", "-b", "0.0.0.0"]